env = Environment()  # Initialize the environment
env.Append(CCFLAGS = ['-g','-std=c++11'])
env.Append(LIBS = ['pthread'])
env.Append(CPPDEFINES={'RELEASE_BUILD' : '1'})
env.Append(LIBPATH = ['/usr/local/lib/'])
env.Append(CPPDEFINES=['BIG_ENDIAN'])
env.Append(CPPPATH = ['/usr/local/include/'])

env.Program(
    target = "cond_test",
    source = "cond_test.cc",
    )
env.Program(
    target = "cond_test2",
    source = "cond_test2.cc",
    )
