
VariantDir(".obj/", "./", duplicate=0);
env = Environment()  # Initialize the environment
env.Append(CCFLAGS = ['-g','-O3'])
#env.Append(LIBS = ['boost_system','boost_filesystem', 'boost_thread'])
env.Append(CPPDEFINES={'RELEASE_BUILD' : '1'})
env.Append(LIBPATH = ['/usr/local/lib/'])
env.Append(CPPDEFINES=['BIG_ENDIAN'])
env.Append(CPPPATH = ['/usr/local/include/', '/usr/lib/jvm/java-8-openjdk-amd64/include/', '/usr/lib/jvm/java-8-openjdk-amd64/include/linux/'])


env.SharedLibrary(
    target = 'shape',
    source = [".obj/swigshape.cpp", ".obj/swigshape_wrap.cxx"]
    )
