// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package org.zhwen.netty.hello;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.zhwen.netty.hello.ReqestType}
   */
  public enum ReqestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0, 0),
    /**
     * <code>SERVICE = 1;</code>
     */
    SERVICE(1, 1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>SERVICE = 1;</code>
     */
    public static final int SERVICE_VALUE = 1;


    public final int getNumber() { return value; }

    public static ReqestType valueOf(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return SERVICE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReqestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ReqestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReqestType>() {
            public ReqestType findValueByNumber(int number) {
              return ReqestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.zhwen.netty.hello.Hello.getDescriptor().getEnumTypes().get(0);
    }

    private static final ReqestType[] VALUES = values();

    public static ReqestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ReqestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.zhwen.netty.hello.ReqestType)
  }

  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .org.zhwen.netty.hello.ReqestType type = 1;
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    org.zhwen.netty.hello.Hello.ReqestType getType();

    // optional .org.zhwen.netty.hello.Login login = 100;
    /**
     * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
     */
    org.zhwen.netty.hello.Hello.Login getLogin();
    /**
     * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
     */
    org.zhwen.netty.hello.Hello.LoginOrBuilder getLoginOrBuilder();

    // optional .org.zhwen.netty.hello.Service service = 101;
    /**
     * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
     */
    boolean hasService();
    /**
     * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
     */
    org.zhwen.netty.hello.Hello.Service getService();
    /**
     * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
     */
    org.zhwen.netty.hello.Hello.ServiceOrBuilder getServiceOrBuilder();
  }
  /**
   * Protobuf type {@code org.zhwen.netty.hello.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.zhwen.netty.hello.Hello.ReqestType value = org.zhwen.netty.hello.Hello.ReqestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 802: {
              org.zhwen.netty.hello.Hello.Login.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(org.zhwen.netty.hello.Hello.Login.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 810: {
              org.zhwen.netty.hello.Hello.Service.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = service_.toBuilder();
              }
              service_ = input.readMessage(org.zhwen.netty.hello.Hello.Service.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(service_);
                service_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhwen.netty.hello.Hello.Request.class, org.zhwen.netty.hello.Hello.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .org.zhwen.netty.hello.ReqestType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.zhwen.netty.hello.Hello.ReqestType type_;
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    public org.zhwen.netty.hello.Hello.ReqestType getType() {
      return type_;
    }

    // optional .org.zhwen.netty.hello.Login login = 100;
    public static final int LOGIN_FIELD_NUMBER = 100;
    private org.zhwen.netty.hello.Hello.Login login_;
    /**
     * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
     */
    public org.zhwen.netty.hello.Hello.Login getLogin() {
      return login_;
    }
    /**
     * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
     */
    public org.zhwen.netty.hello.Hello.LoginOrBuilder getLoginOrBuilder() {
      return login_;
    }

    // optional .org.zhwen.netty.hello.Service service = 101;
    public static final int SERVICE_FIELD_NUMBER = 101;
    private org.zhwen.netty.hello.Hello.Service service_;
    /**
     * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
     */
    public org.zhwen.netty.hello.Hello.Service getService() {
      return service_;
    }
    /**
     * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
     */
    public org.zhwen.netty.hello.Hello.ServiceOrBuilder getServiceOrBuilder() {
      return service_;
    }

    private void initFields() {
      type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
      login_ = org.zhwen.netty.hello.Hello.Login.getDefaultInstance();
      service_ = org.zhwen.netty.hello.Hello.Service.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLogin()) {
        if (!getLogin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(100, login_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(101, service_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(100, login_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, service_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.zhwen.netty.hello.Hello.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.zhwen.netty.hello.Hello.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.zhwen.netty.hello.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.zhwen.netty.hello.Hello.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.zhwen.netty.hello.Hello.Request.class, org.zhwen.netty.hello.Hello.Request.Builder.class);
      }

      // Construct using org.zhwen.netty.hello.Hello.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginFieldBuilder();
          getServiceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (loginBuilder_ == null) {
          login_ = org.zhwen.netty.hello.Hello.Login.getDefaultInstance();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (serviceBuilder_ == null) {
          service_ = org.zhwen.netty.hello.Hello.Service.getDefaultInstance();
        } else {
          serviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Request_descriptor;
      }

      public org.zhwen.netty.hello.Hello.Request getDefaultInstanceForType() {
        return org.zhwen.netty.hello.Hello.Request.getDefaultInstance();
      }

      public org.zhwen.netty.hello.Hello.Request build() {
        org.zhwen.netty.hello.Hello.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.zhwen.netty.hello.Hello.Request buildPartial() {
        org.zhwen.netty.hello.Hello.Request result = new org.zhwen.netty.hello.Hello.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (loginBuilder_ == null) {
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (serviceBuilder_ == null) {
          result.service_ = service_;
        } else {
          result.service_ = serviceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.zhwen.netty.hello.Hello.Request) {
          return mergeFrom((org.zhwen.netty.hello.Hello.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.zhwen.netty.hello.Hello.Request other) {
        if (other == org.zhwen.netty.hello.Hello.Request.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        if (other.hasService()) {
          mergeService(other.getService());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasLogin()) {
          if (!getLogin().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.zhwen.netty.hello.Hello.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.zhwen.netty.hello.Hello.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .org.zhwen.netty.hello.ReqestType type = 1;
      private org.zhwen.netty.hello.Hello.ReqestType type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public org.zhwen.netty.hello.Hello.ReqestType getType() {
        return type_;
      }
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public Builder setType(org.zhwen.netty.hello.Hello.ReqestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
        onChanged();
        return this;
      }

      // optional .org.zhwen.netty.hello.Login login = 100;
      private org.zhwen.netty.hello.Hello.Login login_ = org.zhwen.netty.hello.Hello.Login.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.zhwen.netty.hello.Hello.Login, org.zhwen.netty.hello.Hello.Login.Builder, org.zhwen.netty.hello.Hello.LoginOrBuilder> loginBuilder_;
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public org.zhwen.netty.hello.Hello.Login getLogin() {
        if (loginBuilder_ == null) {
          return login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public Builder setLogin(org.zhwen.netty.hello.Hello.Login value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public Builder setLogin(
          org.zhwen.netty.hello.Hello.Login.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public Builder mergeLogin(org.zhwen.netty.hello.Hello.Login value) {
        if (loginBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              login_ != org.zhwen.netty.hello.Hello.Login.getDefaultInstance()) {
            login_ =
              org.zhwen.netty.hello.Hello.Login.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = org.zhwen.netty.hello.Hello.Login.getDefaultInstance();
          onChanged();
        } else {
          loginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public org.zhwen.netty.hello.Hello.Login.Builder getLoginBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      public org.zhwen.netty.hello.Hello.LoginOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_;
        }
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Login login = 100;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.zhwen.netty.hello.Hello.Login, org.zhwen.netty.hello.Hello.Login.Builder, org.zhwen.netty.hello.Hello.LoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.zhwen.netty.hello.Hello.Login, org.zhwen.netty.hello.Hello.Login.Builder, org.zhwen.netty.hello.Hello.LoginOrBuilder>(
                  login_,
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }

      // optional .org.zhwen.netty.hello.Service service = 101;
      private org.zhwen.netty.hello.Hello.Service service_ = org.zhwen.netty.hello.Hello.Service.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.zhwen.netty.hello.Hello.Service, org.zhwen.netty.hello.Hello.Service.Builder, org.zhwen.netty.hello.Hello.ServiceOrBuilder> serviceBuilder_;
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public org.zhwen.netty.hello.Hello.Service getService() {
        if (serviceBuilder_ == null) {
          return service_;
        } else {
          return serviceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public Builder setService(org.zhwen.netty.hello.Hello.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          service_ = value;
          onChanged();
        } else {
          serviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public Builder setService(
          org.zhwen.netty.hello.Hello.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          service_ = builderForValue.build();
          onChanged();
        } else {
          serviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public Builder mergeService(org.zhwen.netty.hello.Hello.Service value) {
        if (serviceBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              service_ != org.zhwen.netty.hello.Hello.Service.getDefaultInstance()) {
            service_ =
              org.zhwen.netty.hello.Hello.Service.newBuilder(service_).mergeFrom(value).buildPartial();
          } else {
            service_ = value;
          }
          onChanged();
        } else {
          serviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public Builder clearService() {
        if (serviceBuilder_ == null) {
          service_ = org.zhwen.netty.hello.Hello.Service.getDefaultInstance();
          onChanged();
        } else {
          serviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public org.zhwen.netty.hello.Hello.Service.Builder getServiceBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getServiceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      public org.zhwen.netty.hello.Hello.ServiceOrBuilder getServiceOrBuilder() {
        if (serviceBuilder_ != null) {
          return serviceBuilder_.getMessageOrBuilder();
        } else {
          return service_;
        }
      }
      /**
       * <code>optional .org.zhwen.netty.hello.Service service = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.zhwen.netty.hello.Hello.Service, org.zhwen.netty.hello.Hello.Service.Builder, org.zhwen.netty.hello.Hello.ServiceOrBuilder> 
          getServiceFieldBuilder() {
        if (serviceBuilder_ == null) {
          serviceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.zhwen.netty.hello.Hello.Service, org.zhwen.netty.hello.Hello.Service.Builder, org.zhwen.netty.hello.Hello.ServiceOrBuilder>(
                  service_,
                  getParentForChildren(),
                  isClean());
          service_ = null;
        }
        return serviceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.zhwen.netty.hello.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.zhwen.netty.hello.Request)
  }

  public interface LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string user = 1;
    /**
     * <code>required string user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>required string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>required string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    // required string pswd = 2;
    /**
     * <code>required string pswd = 2;</code>
     */
    boolean hasPswd();
    /**
     * <code>required string pswd = 2;</code>
     */
    java.lang.String getPswd();
    /**
     * <code>required string pswd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPswdBytes();
  }
  /**
   * Protobuf type {@code org.zhwen.netty.hello.Login}
   */
  public static final class Login extends
      com.google.protobuf.GeneratedMessage
      implements LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Login(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Login defaultInstance;
    public static Login getDefaultInstance() {
      return defaultInstance;
    }

    public Login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              user_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pswd_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhwen.netty.hello.Hello.Login.class, org.zhwen.netty.hello.Hello.Login.Builder.class);
    }

    public static com.google.protobuf.Parser<Login> PARSER =
        new com.google.protobuf.AbstractParser<Login>() {
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.lang.Object user_;
    /**
     * <code>required string user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string pswd = 2;
    public static final int PSWD_FIELD_NUMBER = 2;
    private java.lang.Object pswd_;
    /**
     * <code>required string pswd = 2;</code>
     */
    public boolean hasPswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string pswd = 2;</code>
     */
    public java.lang.String getPswd() {
      java.lang.Object ref = pswd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pswd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pswd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPswdBytes() {
      java.lang.Object ref = pswd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pswd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      user_ = "";
      pswd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPswd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPswdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPswdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.zhwen.netty.hello.Hello.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.zhwen.netty.hello.Hello.Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.zhwen.netty.hello.Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.zhwen.netty.hello.Hello.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.zhwen.netty.hello.Hello.Login.class, org.zhwen.netty.hello.Hello.Login.Builder.class);
      }

      // Construct using org.zhwen.netty.hello.Hello.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pswd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Login_descriptor;
      }

      public org.zhwen.netty.hello.Hello.Login getDefaultInstanceForType() {
        return org.zhwen.netty.hello.Hello.Login.getDefaultInstance();
      }

      public org.zhwen.netty.hello.Hello.Login build() {
        org.zhwen.netty.hello.Hello.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.zhwen.netty.hello.Hello.Login buildPartial() {
        org.zhwen.netty.hello.Hello.Login result = new org.zhwen.netty.hello.Hello.Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pswd_ = pswd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.zhwen.netty.hello.Hello.Login) {
          return mergeFrom((org.zhwen.netty.hello.Hello.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.zhwen.netty.hello.Hello.Login other) {
        if (other == org.zhwen.netty.hello.Hello.Login.getDefaultInstance()) return this;
        if (other.hasUser()) {
          bitField0_ |= 0x00000001;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasPswd()) {
          bitField0_ |= 0x00000002;
          pswd_ = other.pswd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUser()) {
          
          return false;
        }
        if (!hasPswd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.zhwen.netty.hello.Hello.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.zhwen.netty.hello.Hello.Login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string user = 1;
      private java.lang.Object user_ = "";
      /**
       * <code>required string user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        user_ = value;
        onChanged();
        return this;
      }

      // required string pswd = 2;
      private java.lang.Object pswd_ = "";
      /**
       * <code>required string pswd = 2;</code>
       */
      public boolean hasPswd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string pswd = 2;</code>
       */
      public java.lang.String getPswd() {
        java.lang.Object ref = pswd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pswd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pswd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPswdBytes() {
        java.lang.Object ref = pswd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pswd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pswd = 2;</code>
       */
      public Builder setPswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pswd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pswd = 2;</code>
       */
      public Builder clearPswd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pswd_ = getDefaultInstance().getPswd();
        onChanged();
        return this;
      }
      /**
       * <code>required string pswd = 2;</code>
       */
      public Builder setPswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pswd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.zhwen.netty.hello.Login)
    }

    static {
      defaultInstance = new Login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.zhwen.netty.hello.Login)
  }

  public interface ServiceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string content = 1;
    /**
     * <code>optional string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code org.zhwen.netty.hello.Service}
   */
  public static final class Service extends
      com.google.protobuf.GeneratedMessage
      implements ServiceOrBuilder {
    // Use Service.newBuilder() to construct.
    private Service(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Service(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Service defaultInstance;
    public static Service getDefaultInstance() {
      return defaultInstance;
    }

    public Service getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Service(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Service_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Service_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhwen.netty.hello.Hello.Service.class, org.zhwen.netty.hello.Hello.Service.Builder.class);
    }

    public static com.google.protobuf.Parser<Service> PARSER =
        new com.google.protobuf.AbstractParser<Service>() {
      public Service parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Service(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Service> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string content = 1;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.zhwen.netty.hello.Hello.Service parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Service parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Service parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Service parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.zhwen.netty.hello.Hello.Service prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.zhwen.netty.hello.Service}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.zhwen.netty.hello.Hello.ServiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Service_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Service_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.zhwen.netty.hello.Hello.Service.class, org.zhwen.netty.hello.Hello.Service.Builder.class);
      }

      // Construct using org.zhwen.netty.hello.Hello.Service.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Service_descriptor;
      }

      public org.zhwen.netty.hello.Hello.Service getDefaultInstanceForType() {
        return org.zhwen.netty.hello.Hello.Service.getDefaultInstance();
      }

      public org.zhwen.netty.hello.Hello.Service build() {
        org.zhwen.netty.hello.Hello.Service result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.zhwen.netty.hello.Hello.Service buildPartial() {
        org.zhwen.netty.hello.Hello.Service result = new org.zhwen.netty.hello.Hello.Service(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.zhwen.netty.hello.Hello.Service) {
          return mergeFrom((org.zhwen.netty.hello.Hello.Service)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.zhwen.netty.hello.Hello.Service other) {
        if (other == org.zhwen.netty.hello.Hello.Service.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.zhwen.netty.hello.Hello.Service parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.zhwen.netty.hello.Hello.Service) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string content = 1;
      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.zhwen.netty.hello.Service)
    }

    static {
      defaultInstance = new Service(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.zhwen.netty.hello.Service)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .org.zhwen.netty.hello.ReqestType type = 1;
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    org.zhwen.netty.hello.Hello.ReqestType getType();

    // required int64 seqid = 2;
    /**
     * <code>required int64 seqid = 2;</code>
     */
    boolean hasSeqid();
    /**
     * <code>required int64 seqid = 2;</code>
     */
    long getSeqid();

    // required int32 ret = 3;
    /**
     * <code>required int32 ret = 3;</code>
     */
    boolean hasRet();
    /**
     * <code>required int32 ret = 3;</code>
     */
    int getRet();

    // optional string result = 4;
    /**
     * <code>optional string result = 4;</code>
     */
    boolean hasResult();
    /**
     * <code>optional string result = 4;</code>
     */
    java.lang.String getResult();
    /**
     * <code>optional string result = 4;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code org.zhwen.netty.hello.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.zhwen.netty.hello.Hello.ReqestType value = org.zhwen.netty.hello.Hello.ReqestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              seqid_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ret_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              result_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.zhwen.netty.hello.Hello.Response.class, org.zhwen.netty.hello.Hello.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .org.zhwen.netty.hello.ReqestType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.zhwen.netty.hello.Hello.ReqestType type_;
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
     */
    public org.zhwen.netty.hello.Hello.ReqestType getType() {
      return type_;
    }

    // required int64 seqid = 2;
    public static final int SEQID_FIELD_NUMBER = 2;
    private long seqid_;
    /**
     * <code>required int64 seqid = 2;</code>
     */
    public boolean hasSeqid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 seqid = 2;</code>
     */
    public long getSeqid() {
      return seqid_;
    }

    // required int32 ret = 3;
    public static final int RET_FIELD_NUMBER = 3;
    private int ret_;
    /**
     * <code>required int32 ret = 3;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 ret = 3;</code>
     */
    public int getRet() {
      return ret_;
    }

    // optional string result = 4;
    public static final int RESULT_FIELD_NUMBER = 4;
    private java.lang.Object result_;
    /**
     * <code>optional string result = 4;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string result = 4;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
      seqid_ = 0L;
      ret_ = 0;
      result_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeqid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, seqid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, ret_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getResultBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, seqid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ret_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getResultBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.zhwen.netty.hello.Hello.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.netty.hello.Hello.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.zhwen.netty.hello.Hello.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.zhwen.netty.hello.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.zhwen.netty.hello.Hello.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.zhwen.netty.hello.Hello.Response.class, org.zhwen.netty.hello.Hello.Response.Builder.class);
      }

      // Construct using org.zhwen.netty.hello.Hello.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        seqid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.zhwen.netty.hello.Hello.internal_static_org_zhwen_netty_hello_Response_descriptor;
      }

      public org.zhwen.netty.hello.Hello.Response getDefaultInstanceForType() {
        return org.zhwen.netty.hello.Hello.Response.getDefaultInstance();
      }

      public org.zhwen.netty.hello.Hello.Response build() {
        org.zhwen.netty.hello.Hello.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.zhwen.netty.hello.Hello.Response buildPartial() {
        org.zhwen.netty.hello.Hello.Response result = new org.zhwen.netty.hello.Hello.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seqid_ = seqid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ret_ = ret_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.zhwen.netty.hello.Hello.Response) {
          return mergeFrom((org.zhwen.netty.hello.Hello.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.zhwen.netty.hello.Hello.Response other) {
        if (other == org.zhwen.netty.hello.Hello.Response.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSeqid()) {
          setSeqid(other.getSeqid());
        }
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasResult()) {
          bitField0_ |= 0x00000008;
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSeqid()) {
          
          return false;
        }
        if (!hasRet()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.zhwen.netty.hello.Hello.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.zhwen.netty.hello.Hello.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .org.zhwen.netty.hello.ReqestType type = 1;
      private org.zhwen.netty.hello.Hello.ReqestType type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public org.zhwen.netty.hello.Hello.ReqestType getType() {
        return type_;
      }
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public Builder setType(org.zhwen.netty.hello.Hello.ReqestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.zhwen.netty.hello.ReqestType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.zhwen.netty.hello.Hello.ReqestType.LOGIN;
        onChanged();
        return this;
      }

      // required int64 seqid = 2;
      private long seqid_ ;
      /**
       * <code>required int64 seqid = 2;</code>
       */
      public boolean hasSeqid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 seqid = 2;</code>
       */
      public long getSeqid() {
        return seqid_;
      }
      /**
       * <code>required int64 seqid = 2;</code>
       */
      public Builder setSeqid(long value) {
        bitField0_ |= 0x00000002;
        seqid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 seqid = 2;</code>
       */
      public Builder clearSeqid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seqid_ = 0L;
        onChanged();
        return this;
      }

      // required int32 ret = 3;
      private int ret_ ;
      /**
       * <code>required int32 ret = 3;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 ret = 3;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required int32 ret = 3;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000004;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ret = 3;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ret_ = 0;
        onChanged();
        return this;
      }

      // optional string result = 4;
      private java.lang.Object result_ = "";
      /**
       * <code>optional string result = 4;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string result = 4;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 4;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 4;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000008);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 4;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        result_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.zhwen.netty.hello.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.zhwen.netty.hello.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhwen_netty_hello_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_zhwen_netty_hello_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhwen_netty_hello_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_zhwen_netty_hello_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhwen_netty_hello_Service_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_zhwen_netty_hello_Service_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_zhwen_netty_hello_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_zhwen_netty_hello_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\025org.zhwen.netty.hello\"\230\001\n" +
      "\007Request\022/\n\004type\030\001 \002(\0162!.org.zhwen.netty" +
      ".hello.ReqestType\022+\n\005login\030d \001(\0132\034.org.z" +
      "hwen.netty.hello.Login\022/\n\007service\030e \001(\0132" +
      "\036.org.zhwen.netty.hello.Service\"#\n\005Login" +
      "\022\014\n\004user\030\001 \002(\t\022\014\n\004pswd\030\002 \002(\t\"\032\n\007Service\022" +
      "\017\n\007content\030\001 \001(\t\"g\n\010Response\022/\n\004type\030\001 \002" +
      "(\0162!.org.zhwen.netty.hello.ReqestType\022\r\n" +
      "\005seqid\030\002 \002(\003\022\013\n\003ret\030\003 \002(\005\022\016\n\006result\030\004 \001(" +
      "\t*$\n\nReqestType\022\t\n\005LOGIN\020\000\022\013\n\007SERVICE\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_zhwen_netty_hello_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_zhwen_netty_hello_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_zhwen_netty_hello_Request_descriptor,
              new java.lang.String[] { "Type", "Login", "Service", });
          internal_static_org_zhwen_netty_hello_Login_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_zhwen_netty_hello_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_zhwen_netty_hello_Login_descriptor,
              new java.lang.String[] { "User", "Pswd", });
          internal_static_org_zhwen_netty_hello_Service_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_zhwen_netty_hello_Service_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_zhwen_netty_hello_Service_descriptor,
              new java.lang.String[] { "Content", });
          internal_static_org_zhwen_netty_hello_Response_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_zhwen_netty_hello_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_zhwen_netty_hello_Response_descriptor,
              new java.lang.String[] { "Type", "Seqid", "Ret", "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
