// This file was automatically generated by blade
#ifdef __cplusplus
extern "C" {
#endif

extern const char RESOURCE_status_html[1379];
const uint64_t RESOURCE_status_html_len = 1379;
extern const char RESOURCE_flags_html[1177];
const uint64_t RESOURCE_flags_html_len = 1177;
extern const char RESOURCE_test_html[2672];
const uint64_t RESOURCE_test_html_len = 2672;
extern const char RESOURCE_ServerStatus_types_js[5610];
const uint64_t RESOURCE_ServerStatus_types_js_len = 5610;
extern const char RESOURCE_ServerStatus_js[14064];
const uint64_t RESOURCE_ServerStatus_js_len = 14064;
extern const char RESOURCE_jquery_1_4_2_min_js[72174];
const uint64_t RESOURCE_jquery_1_4_2_min_js_len = 72174;
extern const char RESOURCE_thrift_js[20437];
const uint64_t RESOURCE_thrift_js_len = 20437;

#ifdef __cplusplus
}
#endif

