env = Environment()
env.Append(CCFLAGS = ['-g', '-std=c++11'])
env.Append(LINKFLAGS = ['-static'])

env.Append(LIBS = ['gtest', 'z','pthread'])
thirdparty = "../../thirdparty/"
env.Append(CPPPATH = [thirdparty + 'gtest/include/',
           ])
env.Append(LIBPATH= [thirdparty + '/gtest/lib/',
           ])

env.Program(
	'threadtest',
	['thread_test.cc','base_thread.cc'],
)

env.Program(
	'timestamptest',
	['../main_test.cc', 'timestamp.cc','timestamp_test.cc'],
)

env.Program(
	'condition_var_test',
	['../main_test.cc', 'timestamp.cc', 'condition_var_test.cc'],
)

env.Program(
	'xtimer_test',
	['../main_test.cc',
    'base_thread.cc',
    'timestamp.cc',
    'xtimer.cc',
    'xtimer_test.cc',
    ],
)

#env.Program(
#	'timer_manager_test',
#	['../main_test.cc',
#    'base_thread.cc',
#    'timestamp.cc',
#    'timer_manager.cc',
#    'timer_manager_test.cc',
#    ],
#)
