// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bigtable.proto

package org.zhwen.utils;

public final class Bigtable {
  private Bigtable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BigtableDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:idata.factory.application.game_stat.BigtableData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string primary_key = 1;</code>
     *
     * <pre>
     * qq or commid
     * </pre>
     */
    boolean hasPrimaryKey();
    /**
     * <code>required string primary_key = 1;</code>
     *
     * <pre>
     * qq or commid
     * </pre>
     */
    java.lang.String getPrimaryKey();
    /**
     * <code>required string primary_key = 1;</code>
     *
     * <pre>
     * qq or commid
     * </pre>
     */
    com.google.protobuf.ByteString
        getPrimaryKeyBytes();

    /**
     * <code>repeated int32 level_values = 2;</code>
     *
     * <pre>
     * 特性字段
     * </pre>
     */
    java.util.List<java.lang.Integer> getLevelValuesList();
    /**
     * <code>repeated int32 level_values = 2;</code>
     *
     * <pre>
     * 特性字段
     * </pre>
     */
    int getLevelValuesCount();
    /**
     * <code>repeated int32 level_values = 2;</code>
     *
     * <pre>
     * 特性字段
     * </pre>
     */
    int getLevelValues(int index);
  }
  /**
   * Protobuf type {@code idata.factory.application.game_stat.BigtableData}
   */
  public static final class BigtableData extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:idata.factory.application.game_stat.BigtableData)
      BigtableDataOrBuilder {
    // Use BigtableData.newBuilder() to construct.
    private BigtableData(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BigtableData(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final BigtableData defaultInstance;
    public static BigtableData getDefaultInstance() {
      return defaultInstance;
    }

    public BigtableData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private BigtableData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              primaryKey_ = bs;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                levelValues_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              levelValues_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                levelValues_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                levelValues_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          levelValues_ = java.util.Collections.unmodifiableList(levelValues_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<BigtableData> PARSER =
        new com.google.protobuf.AbstractParser<BigtableData>() {
      public BigtableData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BigtableData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BigtableData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PRIMARY_KEY_FIELD_NUMBER = 1;
    private java.lang.Object primaryKey_;
    /**
     * <code>required string primary_key = 1;</code>
     *
     * <pre>
     * qq or commid
     * </pre>
     */
    public boolean hasPrimaryKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string primary_key = 1;</code>
     *
     * <pre>
     * qq or commid
     * </pre>
     */
    public java.lang.String getPrimaryKey() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          primaryKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string primary_key = 1;</code>
     *
     * <pre>
     * qq or commid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPrimaryKeyBytes() {
      java.lang.Object ref = primaryKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_VALUES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> levelValues_;
    /**
     * <code>repeated int32 level_values = 2;</code>
     *
     * <pre>
     * 特性字段
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getLevelValuesList() {
      return levelValues_;
    }
    /**
     * <code>repeated int32 level_values = 2;</code>
     *
     * <pre>
     * 特性字段
     * </pre>
     */
    public int getLevelValuesCount() {
      return levelValues_.size();
    }
    /**
     * <code>repeated int32 level_values = 2;</code>
     *
     * <pre>
     * 特性字段
     * </pre>
     */
    public int getLevelValues(int index) {
      return levelValues_.get(index);
    }

    private void initFields() {
      primaryKey_ = "";
      levelValues_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPrimaryKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPrimaryKeyBytes());
      }
      for (int i = 0; i < levelValues_.size(); i++) {
        output.writeInt32(2, levelValues_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPrimaryKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < levelValues_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(levelValues_.get(i));
        }
        size += dataSize;
        size += 1 * getLevelValuesList().size();
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.zhwen.utils.Bigtable.BigtableData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.zhwen.utils.Bigtable.BigtableData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code idata.factory.application.game_stat.BigtableData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.zhwen.utils.Bigtable.BigtableData, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:idata.factory.application.game_stat.BigtableData)
        org.zhwen.utils.Bigtable.BigtableDataOrBuilder {
      // Construct using org.zhwen.sparkproject.Bigtable.BigtableData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        primaryKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        levelValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.zhwen.utils.Bigtable.BigtableData getDefaultInstanceForType() {
        return org.zhwen.utils.Bigtable.BigtableData.getDefaultInstance();
      }

      public org.zhwen.utils.Bigtable.BigtableData build() {
        org.zhwen.utils.Bigtable.BigtableData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.zhwen.utils.Bigtable.BigtableData buildPartial() {
        org.zhwen.utils.Bigtable.BigtableData result = new org.zhwen.utils.Bigtable.BigtableData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.primaryKey_ = primaryKey_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          levelValues_ = java.util.Collections.unmodifiableList(levelValues_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.levelValues_ = levelValues_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(org.zhwen.utils.Bigtable.BigtableData other) {
        if (other == org.zhwen.utils.Bigtable.BigtableData.getDefaultInstance()) return this;
        if (other.hasPrimaryKey()) {
          bitField0_ |= 0x00000001;
          primaryKey_ = other.primaryKey_;
          
        }
        if (!other.levelValues_.isEmpty()) {
          if (levelValues_.isEmpty()) {
            levelValues_ = other.levelValues_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLevelValuesIsMutable();
            levelValues_.addAll(other.levelValues_);
          }
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPrimaryKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.zhwen.utils.Bigtable.BigtableData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.zhwen.utils.Bigtable.BigtableData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object primaryKey_ = "";
      /**
       * <code>required string primary_key = 1;</code>
       *
       * <pre>
       * qq or commid
       * </pre>
       */
      public boolean hasPrimaryKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string primary_key = 1;</code>
       *
       * <pre>
       * qq or commid
       * </pre>
       */
      public java.lang.String getPrimaryKey() {
        java.lang.Object ref = primaryKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            primaryKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string primary_key = 1;</code>
       *
       * <pre>
       * qq or commid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPrimaryKeyBytes() {
        java.lang.Object ref = primaryKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string primary_key = 1;</code>
       *
       * <pre>
       * qq or commid
       * </pre>
       */
      public Builder setPrimaryKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        primaryKey_ = value;
        
        return this;
      }
      /**
       * <code>required string primary_key = 1;</code>
       *
       * <pre>
       * qq or commid
       * </pre>
       */
      public Builder clearPrimaryKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        primaryKey_ = getDefaultInstance().getPrimaryKey();
        
        return this;
      }
      /**
       * <code>required string primary_key = 1;</code>
       *
       * <pre>
       * qq or commid
       * </pre>
       */
      public Builder setPrimaryKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        primaryKey_ = value;
        
        return this;
      }

      private java.util.List<java.lang.Integer> levelValues_ = java.util.Collections.emptyList();
      private void ensureLevelValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          levelValues_ = new java.util.ArrayList<java.lang.Integer>(levelValues_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getLevelValuesList() {
        return java.util.Collections.unmodifiableList(levelValues_);
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public int getLevelValuesCount() {
        return levelValues_.size();
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public int getLevelValues(int index) {
        return levelValues_.get(index);
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public Builder setLevelValues(
          int index, int value) {
        ensureLevelValuesIsMutable();
        levelValues_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public Builder addLevelValues(int value) {
        ensureLevelValuesIsMutable();
        levelValues_.add(value);
        
        return this;
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public Builder addAllLevelValues(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLevelValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, levelValues_);
        
        return this;
      }
      /**
       * <code>repeated int32 level_values = 2;</code>
       *
       * <pre>
       * 特性字段
       * </pre>
       */
      public Builder clearLevelValues() {
        levelValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:idata.factory.application.game_stat.BigtableData)
    }

    static {
      defaultInstance = new BigtableData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:idata.factory.application.game_stat.BigtableData)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
