env = Environment()  # Initialize the environment
env.Append(CCFLAGS = ['-g','-O3'])
#env.Append(LINKFLAGS = ['-static'])
env.Append(LIBS = ['hdfs'])
env.Append(LIBPATH = ['/data/hadoop/hadoop/lib/native/'])
env.Append(CPPPATH = ['/data/hadoop/hadoop/include/'])

env.Program(
    target = 'test',
    source = ['test.cc'],
    )
