env = Environment()  # Initialize the environment

#env.Append(CCFLAGS = ['-g','-O3', '-m32'])
env.Append(CCFLAGS = ['-g','-O3'])
env.Append(LINKFLAGS = ['-static'])
env.Append(LIBS = ['hadooppipes','hadooputils', 'pthread', 'crypto', 'z', 'dl'])
env.Append(LIBPATH = ['/data/hadoop/hadoop/lib/native/'])
env.Append(CPPPATH = ['/data/hadoop/hadoop/include/', '/usr/include/x86_64-linux-gnu/'])

env.Program(
    target = 'mr_word_count',
    source = ['mr_word_count.cc'],
    )
