/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef server_status_CONSTANTS_H
#define server_status_CONSTANTS_H

#include "server_status_types.h"

namespace thrift_httpd {

class server_statusConstants {
 public:
  server_statusConstants();

};

extern const server_statusConstants g_server_status_constants;

} // namespace

#endif
