/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server_status_constants.h"

namespace thrift_httpd {

const server_statusConstants g_server_status_constants;

server_statusConstants::server_statusConstants() {
}

} // namespace

