env = Environment()  # Initialize the environment
env.Append(CCFLAGS = ['-g','-std=c++11'])
#env.Append(LIBS = ['boost_system','boost_filesystem', 'boost_thread'])
env.Append(CPPDEFINES={'RELEASE_BUILD' : '1'})
env.Append(LIBPATH = ['/usr/local/lib/'])
env.Append(CPPDEFINES=['BIG_ENDIAN'])
env.Append(CPPPATH = ['/usr/local/include/'])

env.Program(
    target = "funtion",
    source = "funtion.cc",
    )

#env.Program(
#    target = "funtion2",
#    source = "funtion2.cc",
#    )
