/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cityhash {
  public static long CityHash64Mod(String s, long len, long mod) {
    return cityhashJNI.CityHash64Mod(s, len, mod);
  }

  public static long CityHash64IdataMod(String s, long len, long mod) {
    return cityhashJNI.CityHash64IdataMod(s, len, mod);
  }

}
