/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cityhashJNI {
  public final static native long CityHash64Mod(String jarg1, long jarg2, long jarg3);
  public final static native long CityHash64IdataMod(String jarg1, long jarg2, long jarg3);
}
